apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tt-clusterbinding
subjects:
- kind: ServiceAccount
  name: sa-trigger
  namespace: tekton-workers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tt-clusterrole