kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tt-clusterrole
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings", "clusterinterceptors"]
  verbs: ["get", "list", "watch"]